name: "Commit generated C# code"

on:
  workflow_call:

permissions: write-all

jobs:

  commit-job:
    name: "Commit generated C# code"
    runs-on: ubuntu-latest

    steps:
      - name: "Clone Git repository"
        uses: actions/checkout@v2 
        with:
          submodules: 'true'

      - name: "Download changes to commit"
        uses: actions/download-artifact@v1
        with:
          name: "bindgen-cs"
          path: "./src/cs/production/Flecs/"

      - name: "Add + commit + push (if necessary)"
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'HiWill'
          author_email: 'yf_rjxy@live.cn'
          message: "Update C# bindings"
