name: "Pull request"

on:
  workflow_dispatch:

jobs:

  bindgen-job:
    uses: "./.github/workflows/bindgen.yml"

  build-job:
    needs: [bindgen-job]
    if: always()
    uses: "./.github/workflows/build.yml"

  commit-job:
    needs: [bindgen-job, build-job]
    if: github.actor == 'dependabot[bot]'
    uses: "./.github/workflows/commit.yml"
